// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class BidOrderUser
{
    public int Id { get; set; }

    public int? BidOrderUserId { get; set; }

    public int? UserId { get; set; }

    public DateTime BidTransactionTime { get; set; }

    public double? BidTransactionAmount { get; set; }

    public virtual BidOrder BidOrderUserNavigation { get; set; }

    public virtual User User { get; set; }
}