// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class BidOrder
{
    public int Id { get; set; }

    public int? ProductId { get; set; }

    public DateTime BidStartTime { get; set; }

    public DateTime BidEndTime { get; set; }

    public double? BidBasePrice { get; set; }

    public double? BidSoldPrice { get; set; }

    public double? IncrementInPrice { get; set; }

    public TimeOnly IncrementInTime { get; set; }

    public byte[] BidStamp { get; set; }

    public virtual ICollection<BidOrderUser> BidOrderUsers { get; set; } = new List<BidOrderUser>();

    public virtual Product Product { get; set; }
}