// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class CartItemProduct
{
    public int CartItemProductId { get; set; }

    public int ProductsId { get; set; }

    public virtual CartItem CartItemProductNavigation { get; set; }

    public virtual Product Products { get; set; }
}