// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class Connection
{
    public Guid Id { get; set; }

    public int UserId { get; set; }

    public string SignalrId { get; set; }

    public DateTime TimeStamp { get; set; }

    public virtual User User { get; set; }
}