// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class OrderItemProduct
{
    public int OrderItemProductId { get; set; }

    public int ProductsId { get; set; }

    public virtual OrderItem OrderItemProductNavigation { get; set; }

    public virtual Product Products { get; set; }
}