// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class ProductAttribute
{
    public int Id { get; set; }

    public string Type { get; set; }

    public string Value { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public virtual ICollection<ProductAttributesProduct> ProductAttributesProducts { get; set; } = new List<ProductAttributesProduct>();
}