// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class Province
{
    public string Code { get; set; }

    public string Name { get; set; }

    public string NameEn { get; set; }

    public string FullName { get; set; }

    public string FullNameEn { get; set; }

    public string CodeName { get; set; }

    public virtual ICollection<Address> Addresses { get; set; } = new List<Address>();

    public virtual ICollection<District> Districts { get; set; } = new List<District>();
}