// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ArtGalleryManagementSystemAPI.Models;

public partial class WishlistProduct
{
    public int WishlistProductId { get; set; }

    public int ProductsId { get; set; }

    public virtual Product Products { get; set; }

    public virtual Wishlist WishlistProductNavigation { get; set; }
}