USE ARTGALLERY
GO
INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('001',N'Ba Đình',N'Ba Dinh',N'Quận Ba Đình',N'Ba Dinh District','ba_dinh','01'),
('002',N'Hoàn Kiếm',N'Hoan Kiem',N'Quận Hoàn Kiếm',N'Hoan Kiem District','hoan_kiem','01'),
('003',N'Tây Hồ',N'Tay Ho',N'Quận Tây Hồ',N'Tay Ho District','tay_ho','01'),
('004',N'Long Biên',N'Long Bien',N'Quận Long Biên',N'Long Bien District','long_bien','01'),
('005',N'Cầu Giấy',N'Cau Giay',N'Quận Cầu Giấy',N'Cau Giay District','cau_giay','01'),
('006',N'Đống Đa',N'Dong Da',N'Quận Đống Đa',N'Dong Da District','dong_da','01'),
('007',N'Hai Bà Trưng',N'Hai Ba Trung',N'Quận Hai Bà Trưng',N'Hai Ba Trung District','hai_ba_trung','01'),
('008',N'Hoàng Mai',N'Hoang Mai',N'Quận Hoàng Mai',N'Hoang Mai District','hoang_mai','01'),
('009',N'Thanh Xuân',N'Thanh Xuan',N'Quận Thanh Xuân',N'Thanh Xuan District','thanh_xuan','01'),
('016',N'Sóc Sơn',N'Soc Son',N'Huyện Sóc Sơn',N'Soc Son District','soc_son','01'),
('017',N'Đông Anh',N'Dong Anh',N'Huyện Đông Anh',N'Dong Anh District','dong_anh','01'),
('018',N'Gia Lâm',N'Gia Lam',N'Huyện Gia Lâm',N'Gia Lam District','gia_lam','01'),
('019',N'Nam Từ Liêm',N'Nam Tu Liem',N'Quận Nam Từ Liêm',N'Nam Tu Liem District','nam_tu_liem','01'),
('020',N'Thanh Trì',N'Thanh Tri',N'Huyện Thanh Trì',N'Thanh Tri District','thanh_tri','01'),
('021',N'Bắc Từ Liêm',N'Bac Tu Liem',N'Quận Bắc Từ Liêm',N'Bac Tu Liem District','bac_tu_liem','01'),
('024',N'Hà Giang',N'Ha Giang',N'Thành phố Hà Giang',N'Ha Giang City','ha_giang','02'),
('026',N'Đồng Văn',N'Dong Van',N'Huyện Đồng Văn',N'Dong Van District','dong_van','02'),
('027',N'Mèo Vạc',N'Meo Vac',N'Huyện Mèo Vạc',N'Meo Vac District','meo_vac','02'),
('028',N'Yên Minh',N'Yen Minh',N'Huyện Yên Minh',N'Yen Minh District','yen_minh','02'),
('029',N'Quản Bạ',N'Quan Ba',N'Huyện Quản Bạ',N'Quan Ba District','quan_ba','02'),
('030',N'Vị Xuyên',N'Vi Xuyen',N'Huyện Vị Xuyên',N'Vi Xuyen District','vi_xuyen','02'),
('031',N'Bắc Mê',N'Bac Me',N'Huyện Bắc Mê',N'Bac Me District','bac_me','02'),
('032',N'Hoàng Su Phì',N'Hoang Su Phi',N'Huyện Hoàng Su Phì',N'Hoang Su Phi District','hoang_su_phi','02'),
('033',N'Xín Mần',N'Xin Man',N'Huyện Xín Mần',N'Xin Man District','xin_man','02'),
('034',N'Bắc Quang',N'Bac Quang',N'Huyện Bắc Quang',N'Bac Quang District','bac_quang','02'),
('035',N'Quang Bình',N'Quang Binh',N'Huyện Quang Bình',N'Quang Binh District','quang_binh','02'),
('040',N'Cao Bằng',N'Cao Bang',N'Thành phố Cao Bằng',N'Cao Bang City','cao_bang','04'),
('042',N'Bảo Lâm',N'Bao Lam',N'Huyện Bảo Lâm',N'Bao Lam District','bao_lam','04'),
('043',N'Bảo Lạc',N'Bao Lac',N'Huyện Bảo Lạc',N'Bao Lac District','bao_lac','04'),
('045',N'Hà Quảng',N'Ha Quang',N'Huyện Hà Quảng',N'Ha Quang District','ha_quang','04'),
('047',N'Trùng Khánh',N'Trung Khanh',N'Huyện Trùng Khánh',N'Trung Khanh District','trung_khanh','04'),
('048',N'Hạ Lang',N'Ha Lang',N'Huyện Hạ Lang',N'Ha Lang District','ha_lang','04'),
('049',N'Quảng Hòa',N'Quang Hoa',N'Huyện Quảng Hòa',N'Quang Hoa District','quang_hoa','04'),
('051',N'Hoà An',N'Hoa An',N'Huyện Hoà An',N'Hoa An District','hoa_an','04'),
('052',N'Nguyên Bình',N'Nguyen Binh',N'Huyện Nguyên Bình',N'Nguyen Binh District','nguyen_binh','04'),
('053',N'Thạch An',N'Thach An',N'Huyện Thạch An',N'Thach An District','thach_an','04'),
('058',N'Bắc Kạn',N'Bac Kan',N'Thành phố Bắc Kạn',N'Bac Kan City','bac_kan','06'),
('060',N'Pác Nặm',N'Pac Nam',N'Huyện Pác Nặm',N'Pac Nam District','pac_nam','06'),
('061',N'Ba Bể',N'Ba Be',N'Huyện Ba Bể',N'Ba Be District','ba_be','06'),
('062',N'Ngân Sơn',N'Ngan Son',N'Huyện Ngân Sơn',N'Ngan Son District','ngan_son','06'),
('063',N'Bạch Thông',N'Bach Thong',N'Huyện Bạch Thông',N'Bach Thong District','bach_thong','06'),
('064',N'Chợ Đồn',N'Cho Don',N'Huyện Chợ Đồn',N'Cho Don District','cho_don','06'),
('065',N'Chợ Mới',N'Cho Moi',N'Huyện Chợ Mới',N'Cho Moi District','cho_moi','06'),
('066',N'Na Rì',N'Na Ri',N'Huyện Na Rì',N'Na Ri District','na_ri','06'),
('070',N'Tuyên Quang',N'Tuyen Quang',N'Thành phố Tuyên Quang',N'Tuyen Quang City','tuyen_quang','08'),
('071',N'Lâm Bình',N'Lam Binh',N'Huyện Lâm Bình',N'Lam Binh District','lam_binh','08'),
('072',N'Na Hang',N'Na Hang',N'Huyện Na Hang',N'Na Hang District','na_hang','08'),
('073',N'Chiêm Hóa',N'Chiem Hoa',N'Huyện Chiêm Hóa',N'Chiem Hoa District','chiem_hoa','08'),
('074',N'Hàm Yên',N'Ham Yen',N'Huyện Hàm Yên',N'Ham Yen District','ham_yen','08'),
('075',N'Yên Sơn',N'Yen Son',N'Huyện Yên Sơn',N'Yen Son District','yen_son','08');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('076',N'Sơn Dương',N'Son Duong',N'Huyện Sơn Dương',N'Son Duong District','son_duong','08'),
('080',N'Lào Cai',N'Lao Cai',N'Thành phố Lào Cai',N'Lao Cai City','lao_cai','10'),
('082',N'Bát Xát',N'Bat Xat',N'Huyện Bát Xát',N'Bat Xat District','bat_xat','10'),
('083',N'Mường Khương',N'Muong Khuong',N'Huyện Mường Khương',N'Muong Khuong District','muong_khuong','10'),
('084',N'Si Ma Cai',N'Si Ma Cai',N'Huyện Si Ma Cai',N'Si Ma Cai District','si_ma_cai','10'),
('085',N'Bắc Hà',N'Bac Ha',N'Huyện Bắc Hà',N'Bac Ha District','bac_ha','10'),
('086',N'Bảo Thắng',N'Bao Thang',N'Huyện Bảo Thắng',N'Bao Thang District','bao_thang','10'),
('087',N'Bảo Yên',N'Bao Yen',N'Huyện Bảo Yên',N'Bao Yen District','bao_yen','10'),
('088',N'Sa Pa',N'Sa Pa',N'Thị xã Sa Pa',N'Sa Pa Town','sa_pa','10'),
('089',N'Văn Bàn',N'Van Ban',N'Huyện Văn Bàn',N'Van Ban District','van_ban','10'),
('094',N'Điện Biên Phủ',N'Dien Bien Phu',N'Thành phố Điện Biên Phủ',N'Dien Bien Phu City','dien_bien_phu','11'),
('095',N'Mường Lay',N'Muong Lay',N'Thị xã Mường Lay',N'Muong Lay Town','muong_lay','11'),
('096',N'Mường Nhé',N'Muong Nhe',N'Huyện Mường Nhé',N'Muong Nhe District','muong_nhe','11'),
('097',N'Mường Chà',N'Muong Cha',N'Huyện Mường Chà',N'Muong Cha District','muong_cha','11'),
('098',N'Tủa Chùa',N'Tua Chua',N'Huyện Tủa Chùa',N'Tua Chua District','tua_chua','11'),
('099',N'Tuần Giáo',N'Tuan Giao',N'Huyện Tuần Giáo',N'Tuan Giao District','tuan_giao','11'),
('100',N'Điện Biên',N'Dien Bien',N'Huyện Điện Biên',N'Dien Bien District','dien_bien','11'),
('101',N'Điện Biên Đông',N'Dien Bien Dong',N'Huyện Điện Biên Đông',N'Dien Bien Dong District','dien_bien_dong','11'),
('102',N'Mường Ảng',N'Muong Ang',N'Huyện Mường Ảng',N'Muong Ang District','muong_ang','11'),
('103',N'Nậm Pồ',N'Nam Po',N'Huyện Nậm Pồ',N'Nam Po District','nam_po','11'),
('105',N'Lai Châu',N'Lai Chau',N'Thành phố Lai Châu',N'Lai Chau City','lai_chau','12'),
('106',N'Tam Đường',N'Tam Duong',N'Huyện Tam Đường',N'Tam Duong District','tam_duong','12'),
('107',N'Mường Tè',N'Muong Te',N'Huyện Mường Tè',N'Muong Te District','muong_te','12'),
('108',N'Sìn Hồ',N'Sin Ho',N'Huyện Sìn Hồ',N'Sin Ho District','sin_ho','12'),
('109',N'Phong Thổ',N'Phong Tho',N'Huyện Phong Thổ',N'Phong Tho District','phong_tho','12'),
('110',N'Than Uyên',N'Than Uyen',N'Huyện Than Uyên',N'Than Uyen District','than_uyen','12'),
('111',N'Tân Uyên',N'Tan Uyen',N'Huyện Tân Uyên',N'Tan Uyen District','tan_uyen','12'),
('112',N'Nậm Nhùn',N'Nam Nhun',N'Huyện Nậm Nhùn',N'Nam Nhun District','nam_nhun','12'),
('116',N'Sơn La',N'Son La',N'Thành phố Sơn La',N'Son La City','son_la','14'),
('118',N'Quỳnh Nhai',N'Quynh Nhai',N'Huyện Quỳnh Nhai',N'Quynh Nhai District','quynh_nhai','14'),
('119',N'Thuận Châu',N'Thuan Chau',N'Huyện Thuận Châu',N'Thuan Chau District','thuan_chau','14'),
('120',N'Mường La',N'Muong La',N'Huyện Mường La',N'Muong La District','muong_la','14'),
('121',N'Bắc Yên',N'Bac Yen',N'Huyện Bắc Yên',N'Bac Yen District','bac_yen','14'),
('122',N'Phù Yên',N'Phu Yen',N'Huyện Phù Yên',N'Phu Yen District','phu_yen','14'),
('123',N'Mộc Châu',N'Moc Chau',N'Huyện Mộc Châu',N'Moc Chau District','moc_chau','14'),
('124',N'Yên Châu',N'Yen Chau',N'Huyện Yên Châu',N'Yen Chau District','yen_chau','14'),
('125',N'Mai Sơn',N'Mai Son',N'Huyện Mai Sơn',N'Mai Son District','mai_son','14'),
('126',N'Sông Mã',N'Song Ma',N'Huyện Sông Mã',N'Song Ma District','song_ma','14'),
('127',N'Sốp Cộp',N'Sop Cop',N'Huyện Sốp Cộp',N'Sop Cop District','sop_cop','14'),
('128',N'Vân Hồ',N'Van Ho',N'Huyện Vân Hồ',N'Van Ho District','van_ho','14'),
('132',N'Yên Bái',N'Yen Bai',N'Thành phố Yên Bái',N'Yen Bai City','yen_bai','15'),
('133',N'Nghĩa Lộ',N'Nghia Lo',N'Thị xã Nghĩa Lộ',N'Nghia Lo Town','nghia_lo','15'),
('135',N'Lục Yên',N'Luc Yen',N'Huyện Lục Yên',N'Luc Yen District','luc_yen','15'),
('136',N'Văn Yên',N'Van Yen',N'Huyện Văn Yên',N'Van Yen District','van_yen','15'),
('137',N'Mù Căng Chải',N'Mu Cang Chai',N'Huyện Mù Căng Chải',N'Mu Cang Chai District','mu_cang_chai','15'),
('138',N'Trấn Yên',N'Tran Yen',N'Huyện Trấn Yên',N'Tran Yen District','tran_yen','15'),
('139',N'Trạm Tấu',N'Tram Tau',N'Huyện Trạm Tấu',N'Tram Tau District','tram_tau','15'),
('140',N'Văn Chấn',N'Van Chan',N'Huyện Văn Chấn',N'Van Chan District','van_chan','15'),
('141',N'Yên Bình',N'Yen Binh',N'Huyện Yên Bình',N'Yen Binh District','yen_binh','15'),
('148',N'Hòa Bình',N'Hoa Binh',N'Thành phố Hòa Bình',N'Hoa Binh City','hoa_binh','17');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('150',N'Đà Bắc',N'Da Bac',N'Huyện Đà Bắc',N'Da Bac District','da_bac','17'),
('152',N'Lương Sơn',N'Luong Son',N'Huyện Lương Sơn',N'Luong Son District','luong_son','17'),
('153',N'Kim Bôi',N'Kim Boi',N'Huyện Kim Bôi',N'Kim Boi District','kim_boi','17'),
('154',N'Cao Phong',N'Cao Phong',N'Huyện Cao Phong',N'Cao Phong District','cao_phong','17'),
('155',N'Tân Lạc',N'Tan Lac',N'Huyện Tân Lạc',N'Tan Lac District','tan_lac','17'),
('156',N'Mai Châu',N'Mai Chau',N'Huyện Mai Châu',N'Mai Chau District','mai_chau','17'),
('157',N'Lạc Sơn',N'Lac Son',N'Huyện Lạc Sơn',N'Lac Son District','lac_son','17'),
('158',N'Yên Thủy',N'Yen Thuy',N'Huyện Yên Thủy',N'Yen Thuy District','yen_thuy','17'),
('159',N'Lạc Thủy',N'Lac Thuy',N'Huyện Lạc Thủy',N'Lac Thuy District','lac_thuy','17'),
('164',N'Thái Nguyên',N'Thai Nguyen',N'Thành phố Thái Nguyên',N'Thai Nguyen City','thai_nguyen','19'),
('165',N'Sông Công',N'Song Cong',N'Thành phố Sông Công',N'Song Cong City','song_cong','19'),
('167',N'Định Hóa',N'Dinh Hoa',N'Huyện Định Hóa',N'Dinh Hoa District','dinh_hoa','19'),
('168',N'Phú Lương',N'Phu Luong',N'Huyện Phú Lương',N'Phu Luong District','phu_luong','19'),
('169',N'Đồng Hỷ',N'Dong Hy',N'Huyện Đồng Hỷ',N'Dong Hy District','dong_hy','19'),
('170',N'Võ Nhai',N'Vo Nhai',N'Huyện Võ Nhai',N'Vo Nhai District','vo_nhai','19'),
('171',N'Đại Từ',N'Dai Tu',N'Huyện Đại Từ',N'Dai Tu District','dai_tu','19'),
('172',N'Phổ Yên',N'Pho Yen',N'Thành phố Phổ Yên',N'Pho Yen City','pho_yen','19'),
('173',N'Phú Bình',N'Phu Binh',N'Huyện Phú Bình',N'Phu Binh District','phu_binh','19'),
('178',N'Lạng Sơn',N'Lang Son',N'Thành phố Lạng Sơn',N'Lang Son City','lang_son','20'),
('180',N'Tràng Định',N'Trang Dinh',N'Huyện Tràng Định',N'Trang Dinh District','trang_dinh','20'),
('181',N'Bình Gia',N'Binh Gia',N'Huyện Bình Gia',N'Binh Gia District','binh_gia','20'),
('182',N'Văn Lãng',N'Van Lang',N'Huyện Văn Lãng',N'Van Lang District','van_lang','20'),
('183',N'Cao Lộc',N'Cao Loc',N'Huyện Cao Lộc',N'Cao Loc District','cao_loc','20'),
('184',N'Văn Quan',N'Van Quan',N'Huyện Văn Quan',N'Van Quan District','van_quan','20'),
('185',N'Bắc Sơn',N'Bac Son',N'Huyện Bắc Sơn',N'Bac Son District','bac_son','20'),
('186',N'Hữu Lũng',N'Huu Lung',N'Huyện Hữu Lũng',N'Huu Lung District','huu_lung','20'),
('187',N'Chi Lăng',N'Chi Lang',N'Huyện Chi Lăng',N'Chi Lang District','chi_lang','20'),
('188',N'Lộc Bình',N'Loc Binh',N'Huyện Lộc Bình',N'Loc Binh District','loc_binh','20'),
('189',N'Đình Lập',N'Dinh Lap',N'Huyện Đình Lập',N'Dinh Lap District','dinh_lap','20'),
('193',N'Hạ Long',N'Ha Long',N'Thành phố Hạ Long',N'Ha Long City','ha_long','22'),
('194',N'Móng Cái',N'Mong Cai',N'Thành phố Móng Cái',N'Mong Cai City','mong_cai','22'),
('195',N'Cẩm Phả',N'Cam Pha',N'Thành phố Cẩm Phả',N'Cam Pha City','cam_pha','22'),
('196',N'Uông Bí',N'Uong Bi',N'Thành phố Uông Bí',N'Uong Bi City','uong_bi','22'),
('198',N'Bình Liêu',N'Binh Lieu',N'Huyện Bình Liêu',N'Binh Lieu District','binh_lieu','22'),
('199',N'Tiên Yên',N'Tien Yen',N'Huyện Tiên Yên',N'Tien Yen District','tien_yen','22'),
('200',N'Đầm Hà',N'Dam Ha',N'Huyện Đầm Hà',N'Dam Ha District','dam_ha','22'),
('201',N'Hải Hà',N'Hai Ha',N'Huyện Hải Hà',N'Hai Ha District','hai_ha','22'),
('202',N'Ba Chẽ',N'Ba Che',N'Huyện Ba Chẽ',N'Ba Che District','ba_che','22'),
('203',N'Vân Đồn',N'Van Don',N'Huyện Vân Đồn',N'Van Don District','van_don','22'),
('205',N'Đông Triều',N'Dong Trieu',N'Thị xã Đông Triều',N'Dong Trieu Town','dong_trieu','22'),
('206',N'Quảng Yên',N'Quang Yen',N'Thị xã Quảng Yên',N'Quang Yen Town','quang_yen','22'),
('207',N'Cô Tô',N'Co To',N'Huyện Cô Tô',N'Co To District','co_to','22'),
('213',N'Bắc Giang',N'Bac Giang',N'Thành phố Bắc Giang',N'Bac Giang City','bac_giang','24'),
('215',N'Yên Thế',N'Yen The',N'Huyện Yên Thế',N'Yen The District','yen_the','24'),
('216',N'Tân Yên',N'Tan Yen',N'Huyện Tân Yên',N'Tan Yen District','tan_yen','24'),
('217',N'Lạng Giang',N'Lang Giang',N'Huyện Lạng Giang',N'Lang Giang District','lang_giang','24'),
('218',N'Lục Nam',N'Luc Nam',N'Huyện Lục Nam',N'Luc Nam District','luc_nam','24'),
('219',N'Lục Ngạn',N'Luc Ngan',N'Huyện Lục Ngạn',N'Luc Ngan District','luc_ngan','24'),
('220',N'Sơn Động',N'Son Dong',N'Huyện Sơn Động',N'Son Dong District','son_dong','24'),
('221',N'Yên Dũng',N'Yen Dung',N'Huyện Yên Dũng',N'Yen Dung District','yen_dung','24');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('222',N'Việt Yên',N'Viet Yen',N'Thị xã Việt Yên',N'Viet Yen Town','viet_yen','24'),
('223',N'Hiệp Hòa',N'Hiep Hoa',N'Huyện Hiệp Hòa',N'Hiep Hoa District','hiep_hoa','24'),
('227',N'Việt Trì',N'Viet Tri',N'Thành phố Việt Trì',N'Viet Tri City','viet_tri','25'),
('228',N'Phú Thọ',N'Phu Tho',N'Thị xã Phú Thọ',N'Phu Tho Town','phu_tho','25'),
('230',N'Đoan Hùng',N'Doan Hung',N'Huyện Đoan Hùng',N'Doan Hung District','doan_hung','25'),
('231',N'Hạ Hoà',N'Ha Hoa',N'Huyện Hạ Hoà',N'Ha Hoa District','ha_hoa','25'),
('232',N'Thanh Ba',N'Thanh Ba',N'Huyện Thanh Ba',N'Thanh Ba District','thanh_ba','25'),
('233',N'Phù Ninh',N'Phu Ninh',N'Huyện Phù Ninh',N'Phu Ninh District','phu_ninh','25'),
('234',N'Yên Lập',N'Yen Lap',N'Huyện Yên Lập',N'Yen Lap District','yen_lap','25'),
('235',N'Cẩm Khê',N'Cam Khe',N'Huyện Cẩm Khê',N'Cam Khe District','cam_khe','25'),
('236',N'Tam Nông',N'Tam Nong',N'Huyện Tam Nông',N'Tam Nong District','tam_nong','25'),
('237',N'Lâm Thao',N'Lam Thao',N'Huyện Lâm Thao',N'Lam Thao District','lam_thao','25'),
('238',N'Thanh Sơn',N'Thanh Son',N'Huyện Thanh Sơn',N'Thanh Son District','thanh_son','25'),
('239',N'Thanh Thuỷ',N'Thanh Thuy',N'Huyện Thanh Thuỷ',N'Thanh Thuy District','thanh_thuy','25'),
('240',N'Tân Sơn',N'Tan Son',N'Huyện Tân Sơn',N'Tan Son District','tan_son','25'),
('243',N'Vĩnh Yên',N'Vinh Yen',N'Thành phố Vĩnh Yên',N'Vinh Yen City','vinh_yen','26'),
('244',N'Phúc Yên',N'Phuc Yen',N'Thành phố Phúc Yên',N'Phuc Yen City','phuc_yen','26'),
('246',N'Lập Thạch',N'Lap Thach',N'Huyện Lập Thạch',N'Lap Thach District','lap_thach','26'),
('247',N'Tam Dương',N'Tam Duong',N'Huyện Tam Dương',N'Tam Duong District','tam_duong','26'),
('248',N'Tam Đảo',N'Tam Dao',N'Huyện Tam Đảo',N'Tam Dao District','tam_dao','26'),
('249',N'Bình Xuyên',N'Binh Xuyen',N'Huyện Bình Xuyên',N'Binh Xuyen District','binh_xuyen','26'),
('250',N'Mê Linh',N'Me Linh',N'Huyện Mê Linh',N'Me Linh District','me_linh','01'),
('251',N'Yên Lạc',N'Yen Lac',N'Huyện Yên Lạc',N'Yen Lac District','yen_lac','26'),
('252',N'Vĩnh Tường',N'Vinh Tuong',N'Huyện Vĩnh Tường',N'Vinh Tuong District','vinh_tuong','26'),
('253',N'Sông Lô',N'Song Lo',N'Huyện Sông Lô',N'Song Lo District','song_lo','26'),
('256',N'Bắc Ninh',N'Bac Ninh',N'Thành phố Bắc Ninh',N'Bac Ninh City','bac_ninh','27'),
('258',N'Yên Phong',N'Yen Phong',N'Huyện Yên Phong',N'Yen Phong District','yen_phong','27'),
('259',N'Quế Võ',N'Que Vo',N'Thị xã Quế Võ',N'Que Vo Town','que_vo','27'),
('260',N'Tiên Du',N'Tien Du',N'Huyện Tiên Du',N'Tien Du District','tien_du','27'),
('261',N'Từ Sơn',N'Tu Son',N'Thành phố Từ Sơn',N'Tu Son City','tu_son','27'),
('262',N'Thuận Thành',N'Thuan Thanh',N'Thị xã Thuận Thành',N'Thuan Thanh Town','thuan_thanh','27'),
('263',N'Gia Bình',N'Gia Binh',N'Huyện Gia Bình',N'Gia Binh District','gia_binh','27'),
('264',N'Lương Tài',N'Luong Tai',N'Huyện Lương Tài',N'Luong Tai District','luong_tai','27'),
('268',N'Hà Đông',N'Ha Dong',N'Quận Hà Đông',N'Ha Dong District','ha_dong','01'),
('269',N'Sơn Tây',N'Son Tay',N'Thị xã Sơn Tây',N'Son Tay Town','son_tay','01'),
('271',N'Ba Vì',N'Ba Vi',N'Huyện Ba Vì',N'Ba Vi District','ba_vi','01'),
('272',N'Phúc Thọ',N'Phuc Tho',N'Huyện Phúc Thọ',N'Phuc Tho District','phuc_tho','01'),
('273',N'Đan Phượng',N'Dan Phuong',N'Huyện Đan Phượng',N'Dan Phuong District','dan_phuong','01'),
('274',N'Hoài Đức',N'Hoai Duc',N'Huyện Hoài Đức',N'Hoai Duc District','hoai_duc','01'),
('275',N'Quốc Oai',N'Quoc Oai',N'Huyện Quốc Oai',N'Quoc Oai District','quoc_oai','01'),
('276',N'Thạch Thất',N'Thach That',N'Huyện Thạch Thất',N'Thach That District','thach_that','01'),
('277',N'Chương Mỹ',N'Chuong My',N'Huyện Chương Mỹ',N'Chuong My District','chuong_my','01'),
('278',N'Thanh Oai',N'Thanh Oai',N'Huyện Thanh Oai',N'Thanh Oai District','thanh_oai','01'),
('279',N'Thường Tín',N'Thuong Tin',N'Huyện Thường Tín',N'Thuong Tin District','thuong_tin','01'),
('280',N'Phú Xuyên',N'Phu Xuyen',N'Huyện Phú Xuyên',N'Phu Xuyen District','phu_xuyen','01'),
('281',N'Ứng Hòa',N'Ung Hoa',N'Huyện Ứng Hòa',N'Ung Hoa District','ung_hoa','01'),
('282',N'Mỹ Đức',N'My Duc',N'Huyện Mỹ Đức',N'My Duc District','my_duc','01'),
('288',N'Hải Dương',N'Hai Duong',N'Thành phố Hải Dương',N'Hai Duong City','hai_duong','30'),
('290',N'Chí Linh',N'Chi Linh',N'Thành phố Chí Linh',N'Chi Linh City','chi_linh','30'),
('291',N'Nam Sách',N'Nam Sach',N'Huyện Nam Sách',N'Nam Sach District','nam_sach','30');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('292',N'Kinh Môn',N'Kinh Mon',N'Thị xã Kinh Môn',N'Kinh Mon Town','kinh_mon','30'),
('293',N'Kim Thành',N'Kim Thanh',N'Huyện Kim Thành',N'Kim Thanh District','kim_thanh','30'),
('294',N'Thanh Hà',N'Thanh Ha',N'Huyện Thanh Hà',N'Thanh Ha District','thanh_ha','30'),
('295',N'Cẩm Giàng',N'Cam Giang',N'Huyện Cẩm Giàng',N'Cam Giang District','cam_giang','30'),
('296',N'Bình Giang',N'Binh Giang',N'Huyện Bình Giang',N'Binh Giang District','binh_giang','30'),
('297',N'Gia Lộc',N'Gia Loc',N'Huyện Gia Lộc',N'Gia Loc District','gia_loc','30'),
('298',N'Tứ Kỳ',N'Tu Ky',N'Huyện Tứ Kỳ',N'Tu Ky District','tu_ky','30'),
('299',N'Ninh Giang',N'Ninh Giang',N'Huyện Ninh Giang',N'Ninh Giang District','ninh_giang','30'),
('300',N'Thanh Miện',N'Thanh Mien',N'Huyện Thanh Miện',N'Thanh Mien District','thanh_mien','30'),
('303',N'Hồng Bàng',N'Hong Bang',N'Quận Hồng Bàng',N'Hong Bang District','hong_bang','31'),
('304',N'Ngô Quyền',N'Ngo Quyen',N'Quận Ngô Quyền',N'Ngo Quyen District','ngo_quyen','31'),
('305',N'Lê Chân',N'Le Chan',N'Quận Lê Chân',N'Le Chan District','le_chan','31'),
('306',N'Hải An',N'Hai An',N'Quận Hải An',N'Hai An District','hai_an','31'),
('307',N'Kiến An',N'Kien An',N'Quận Kiến An',N'Kien An District','kien_an','31'),
('308',N'Đồ Sơn',N'Do Son',N'Quận Đồ Sơn',N'Do Son District','do_son','31'),
('309',N'Dương Kinh',N'Duong Kinh',N'Quận Dương Kinh',N'Duong Kinh District','duong_kinh','31'),
('311',N'Thuỷ Nguyên',N'Thuy Nguyen',N'Huyện Thuỷ Nguyên',N'Thuy Nguyen District','thuy_nguyen','31'),
('312',N'An Dương',N'An Duong',N'Huyện An Dương',N'An Duong District','an_duong','31'),
('313',N'An Lão',N'An Lao',N'Huyện An Lão',N'An Lao District','an_lao','31'),
('314',N'Kiến Thuỵ',N'Kien Thuy',N'Huyện Kiến Thuỵ',N'Kien Thuy District','kien_thuy','31'),
('315',N'Tiên Lãng',N'Tien Lang',N'Huyện Tiên Lãng',N'Tien Lang District','tien_lang','31'),
('316',N'Vĩnh Bảo',N'Vinh Bao',N'Huyện Vĩnh Bảo',N'Vinh Bao District','vinh_bao','31'),
('317',N'Cát Hải',N'Cat Hai',N'Huyện Cát Hải',N'Cat Hai District','cat_hai','31'),
('323',N'Hưng Yên',N'Hung Yen',N'Thành phố Hưng Yên',N'Hung Yen City','hung_yen','33'),
('325',N'Văn Lâm',N'Van Lam',N'Huyện Văn Lâm',N'Van Lam District','van_lam','33'),
('326',N'Văn Giang',N'Van Giang',N'Huyện Văn Giang',N'Van Giang District','van_giang','33'),
('327',N'Yên Mỹ',N'Yen My',N'Huyện Yên Mỹ',N'Yen My District','yen_my','33'),
('328',N'Mỹ Hào',N'My Hao',N'Thị xã Mỹ Hào',N'My Hao Town','my_hao','33'),
('329',N'Ân Thi',N'An Thi',N'Huyện Ân Thi',N'An Thi District','an_thi','33'),
('330',N'Khoái Châu',N'Khoai Chau',N'Huyện Khoái Châu',N'Khoai Chau District','khoai_chau','33'),
('331',N'Kim Động',N'Kim Dong',N'Huyện Kim Động',N'Kim Dong District','kim_dong','33'),
('332',N'Tiên Lữ',N'Tien Lu',N'Huyện Tiên Lữ',N'Tien Lu District','tien_lu','33'),
('333',N'Phù Cừ',N'Phu Cu',N'Huyện Phù Cừ',N'Phu Cu District','phu_cu','33'),
('336',N'Thái Bình',N'Thai Binh',N'Thành phố Thái Bình',N'Thai Binh City','thai_binh','34'),
('338',N'Quỳnh Phụ',N'Quynh Phu',N'Huyện Quỳnh Phụ',N'Quynh Phu District','quynh_phu','34'),
('339',N'Hưng Hà',N'Hung Ha',N'Huyện Hưng Hà',N'Hung Ha District','hung_ha','34'),
('340',N'Đông Hưng',N'Dong Hung',N'Huyện Đông Hưng',N'Dong Hung District','dong_hung','34'),
('341',N'Thái Thụy',N'Thai Thuy',N'Huyện Thái Thụy',N'Thai Thuy District','thai_thuy','34'),
('342',N'Tiền Hải',N'Tien Hai',N'Huyện Tiền Hải',N'Tien Hai District','tien_hai','34'),
('343',N'Kiến Xương',N'Kien Xuong',N'Huyện Kiến Xương',N'Kien Xuong District','kien_xuong','34'),
('344',N'Vũ Thư',N'Vu Thu',N'Huyện Vũ Thư',N'Vu Thu District','vu_thu','34'),
('347',N'Phủ Lý',N'Phu Ly',N'Thành phố Phủ Lý',N'Phu Ly City','phu_ly','35'),
('349',N'Duy Tiên',N'Duy Tien',N'Thị xã Duy Tiên',N'Duy Tien Town','duy_tien','35'),
('350',N'Kim Bảng',N'Kim Bang',N'Huyện Kim Bảng',N'Kim Bang District','kim_bang','35'),
('351',N'Thanh Liêm',N'Thanh Liem',N'Huyện Thanh Liêm',N'Thanh Liem District','thanh_liem','35'),
('352',N'Bình Lục',N'Binh Luc',N'Huyện Bình Lục',N'Binh Luc District','binh_luc','35'),
('353',N'Lý Nhân',N'Ly Nhan',N'Huyện Lý Nhân',N'Ly Nhan District','ly_nhan','35'),
('356',N'Nam Định',N'Nam Dinh',N'Thành phố Nam Định',N'Nam Dinh City','nam_dinh','36'),
('359',N'Vụ Bản',N'Vu Ban',N'Huyện Vụ Bản',N'Vu Ban District','vu_ban','36'),
('360',N'Ý Yên',N'Y Yen',N'Huyện Ý Yên',N'Y Yen District','y_yen','36');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('361',N'Nghĩa Hưng',N'Nghia Hung',N'Huyện Nghĩa Hưng',N'Nghia Hung District','nghia_hung','36'),
('362',N'Nam Trực',N'Nam Truc',N'Huyện Nam Trực',N'Nam Truc District','nam_truc','36'),
('363',N'Trực Ninh',N'Truc Ninh',N'Huyện Trực Ninh',N'Truc Ninh District','truc_ninh','36'),
('364',N'Xuân Trường',N'Xuan Truong',N'Huyện Xuân Trường',N'Xuan Truong District','xuan_truong','36'),
('365',N'Giao Thủy',N'Giao Thuy',N'Huyện Giao Thủy',N'Giao Thuy District','giao_thuy','36'),
('366',N'Hải Hậu',N'Hai Hau',N'Huyện Hải Hậu',N'Hai Hau District','hai_hau','36'),
('369',N'Ninh Bình',N'Ninh Binh',N'Thành phố Ninh Bình',N'Ninh Binh City','ninh_binh','37'),
('370',N'Tam Điệp',N'Tam Diep',N'Thành phố Tam Điệp',N'Tam Diep City','tam_diep','37'),
('372',N'Nho Quan',N'Nho Quan',N'Huyện Nho Quan',N'Nho Quan District','nho_quan','37'),
('373',N'Gia Viễn',N'Gia Vien',N'Huyện Gia Viễn',N'Gia Vien District','gia_vien','37'),
('374',N'Hoa Lư',N'Hoa Lu',N'Huyện Hoa Lư',N'Hoa Lu District','hoa_lu','37'),
('375',N'Yên Khánh',N'Yen Khanh',N'Huyện Yên Khánh',N'Yen Khanh District','yen_khanh','37'),
('376',N'Kim Sơn',N'Kim Son',N'Huyện Kim Sơn',N'Kim Son District','kim_son','37'),
('377',N'Yên Mô',N'Yen Mo',N'Huyện Yên Mô',N'Yen Mo District','yen_mo','37'),
('380',N'Thanh Hóa',N'Thanh Hoa',N'Thành phố Thanh Hóa',N'Thanh Hoa City','thanh_hoa','38'),
('381',N'Bỉm Sơn',N'Bim Son',N'Thị xã Bỉm Sơn',N'Bim Son Town','bim_son','38'),
('382',N'Sầm Sơn',N'Sam Son',N'Thành phố Sầm Sơn',N'Sam Son City','sam_son','38'),
('384',N'Mường Lát',N'Muong Lat',N'Huyện Mường Lát',N'Muong Lat District','muong_lat','38'),
('385',N'Quan Hóa',N'Quan Hoa',N'Huyện Quan Hóa',N'Quan Hoa District','quan_hoa','38'),
('386',N'Bá Thước',N'Ba Thuoc',N'Huyện Bá Thước',N'Ba Thuoc District','ba_thuoc','38'),
('387',N'Quan Sơn',N'Quan Son',N'Huyện Quan Sơn',N'Quan Son District','quan_son','38'),
('388',N'Lang Chánh',N'Lang Chanh',N'Huyện Lang Chánh',N'Lang Chanh District','lang_chanh','38'),
('389',N'Ngọc Lặc',N'Ngoc Lac',N'Huyện Ngọc Lặc',N'Ngoc Lac District','ngoc_lac','38'),
('390',N'Cẩm Thủy',N'Cam Thuy',N'Huyện Cẩm Thủy',N'Cam Thuy District','cam_thuy','38'),
('391',N'Thạch Thành',N'Thach Thanh',N'Huyện Thạch Thành',N'Thach Thanh District','thach_thanh','38'),
('392',N'Hà Trung',N'Ha Trung',N'Huyện Hà Trung',N'Ha Trung District','ha_trung','38'),
('393',N'Vĩnh Lộc',N'Vinh Loc',N'Huyện Vĩnh Lộc',N'Vinh Loc District','vinh_loc','38'),
('394',N'Yên Định',N'Yen Dinh',N'Huyện Yên Định',N'Yen Dinh District','yen_dinh','38'),
('395',N'Thọ Xuân',N'Tho Xuan',N'Huyện Thọ Xuân',N'Tho Xuan District','tho_xuan','38'),
('396',N'Thường Xuân',N'Thuong Xuan',N'Huyện Thường Xuân',N'Thuong Xuan District','thuong_xuan','38'),
('397',N'Triệu Sơn',N'Trieu Son',N'Huyện Triệu Sơn',N'Trieu Son District','trieu_son','38'),
('398',N'Thiệu Hóa',N'Thieu Hoa',N'Huyện Thiệu Hóa',N'Thieu Hoa District','thieu_hoa','38'),
('399',N'Hoằng Hóa',N'Hoang Hoa',N'Huyện Hoằng Hóa',N'Hoang Hoa District','hoang_hoa','38'),
('400',N'Hậu Lộc',N'Hau Loc',N'Huyện Hậu Lộc',N'Hau Loc District','hau_loc','38'),
('401',N'Nga Sơn',N'Nga Son',N'Huyện Nga Sơn',N'Nga Son District','nga_son','38'),
('402',N'Như Xuân',N'Nhu Xuan',N'Huyện Như Xuân',N'Nhu Xuan District','nhu_xuan','38'),
('403',N'Như Thanh',N'Nhu Thanh',N'Huyện Như Thanh',N'Nhu Thanh District','nhu_thanh','38'),
('404',N'Nông Cống',N'Nong Cong',N'Huyện Nông Cống',N'Nong Cong District','nong_cong','38'),
('405',N'Đông Sơn',N'Dong Son',N'Huyện Đông Sơn',N'Dong Son District','dong_son','38'),
('406',N'Quảng Xương',N'Quang Xuong',N'Huyện Quảng Xương',N'Quang Xuong District','quang_xuong','38'),
('407',N'Nghi Sơn',N'Nghi Son',N'Thị xã Nghi Sơn',N'Nghi Son Town','nghi_son','38'),
('412',N'Vinh',N'Vinh',N'Thành phố Vinh',N'Vinh City','vinh','40'),
('413',N'Cửa Lò',N'Cua Lo',N'Thị xã Cửa Lò',N'Cua Lo Town','cua_lo','40'),
('414',N'Thái Hoà',N'Thai Hoa',N'Thị xã Thái Hoà',N'Thai Hoa Town','thai_hoa','40'),
('415',N'Quế Phong',N'Que Phong',N'Huyện Quế Phong',N'Que Phong District','que_phong','40'),
('416',N'Quỳ Châu',N'Quy Chau',N'Huyện Quỳ Châu',N'Quy Chau District','quy_chau','40'),
('417',N'Kỳ Sơn',N'Ky Son',N'Huyện Kỳ Sơn',N'Ky Son District','ky_son','40'),
('418',N'Tương Dương',N'Tuong Duong',N'Huyện Tương Dương',N'Tuong Duong District','tuong_duong','40'),
('419',N'Nghĩa Đàn',N'Nghia Dan',N'Huyện Nghĩa Đàn',N'Nghia Dan District','nghia_dan','40'),
('420',N'Quỳ Hợp',N'Quy Hop',N'Huyện Quỳ Hợp',N'Quy Hop District','quy_hop','40');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('421',N'Quỳnh Lưu',N'Quynh Luu',N'Huyện Quỳnh Lưu',N'Quynh Luu District','quynh_luu','40'),
('422',N'Con Cuông',N'Con Cuong',N'Huyện Con Cuông',N'Con Cuong District','con_cuong','40'),
('423',N'Tân Kỳ',N'Tan Ky',N'Huyện Tân Kỳ',N'Tan Ky District','tan_ky','40'),
('424',N'Anh Sơn',N'Anh Son',N'Huyện Anh Sơn',N'Anh Son District','anh_son','40'),
('425',N'Diễn Châu',N'Dien Chau',N'Huyện Diễn Châu',N'Dien Chau District','dien_chau','40'),
('426',N'Yên Thành',N'Yen Thanh',N'Huyện Yên Thành',N'Yen Thanh District','yen_thanh','40'),
('427',N'Đô Lương',N'Do Luong',N'Huyện Đô Lương',N'Do Luong District','do_luong','40'),
('428',N'Thanh Chương',N'Thanh Chuong',N'Huyện Thanh Chương',N'Thanh Chuong District','thanh_chuong','40'),
('429',N'Nghi Lộc',N'Nghi Loc',N'Huyện Nghi Lộc',N'Nghi Loc District','nghi_loc','40'),
('430',N'Nam Đàn',N'Nam Dan',N'Huyện Nam Đàn',N'Nam Dan District','nam_dan','40'),
('431',N'Hưng Nguyên',N'Hung Nguyen',N'Huyện Hưng Nguyên',N'Hung Nguyen District','hung_nguyen','40'),
('432',N'Hoàng Mai',N'Hoang Mai',N'Thị xã Hoàng Mai',N'Hoang Mai Town','hoang_mai','40'),
('436',N'Hà Tĩnh',N'Ha Tinh',N'Thành phố Hà Tĩnh',N'Ha Tinh City','ha_tinh','42'),
('437',N'Hồng Lĩnh',N'Hong Linh',N'Thị xã Hồng Lĩnh',N'Hong Linh Town','hong_linh','42'),
('439',N'Hương Sơn',N'Huong Son',N'Huyện Hương Sơn',N'Huong Son District','huong_son','42'),
('440',N'Đức Thọ',N'Duc Tho',N'Huyện Đức Thọ',N'Duc Tho District','duc_tho','42'),
('441',N'Vũ Quang',N'Vu Quang',N'Huyện Vũ Quang',N'Vu Quang District','vu_quang','42'),
('442',N'Nghi Xuân',N'Nghi Xuan',N'Huyện Nghi Xuân',N'Nghi Xuan District','nghi_xuan','42'),
('443',N'Can Lộc',N'Can Loc',N'Huyện Can Lộc',N'Can Loc District','can_loc','42'),
('444',N'Hương Khê',N'Huong Khe',N'Huyện Hương Khê',N'Huong Khe District','huong_khe','42'),
('445',N'Thạch Hà',N'Thach Ha',N'Huyện Thạch Hà',N'Thach Ha District','thach_ha','42'),
('446',N'Cẩm Xuyên',N'Cam Xuyen',N'Huyện Cẩm Xuyên',N'Cam Xuyen District','cam_xuyen','42'),
('447',N'Kỳ Anh',N'Ky Anh',N'Huyện Kỳ Anh',N'Ky Anh District','ky_anh','42'),
('448',N'Lộc Hà',N'Loc Ha',N'Huyện Lộc Hà',N'Loc Ha District','loc_ha','42'),
('449',N'Kỳ Anh',N'Ky Anh',N'Thị xã Kỳ Anh',N'Ky Anh Town','ky_anh','42'),
('450',N'Đồng Hới',N'Dong Hoi',N'Thành phố Đồng Hới',N'Dong Hoi City','dong_hoi','44'),
('452',N'Minh Hóa',N'Minh Hoa',N'Huyện Minh Hóa',N'Minh Hoa District','minh_hoa','44'),
('453',N'Tuyên Hóa',N'Tuyen Hoa',N'Huyện Tuyên Hóa',N'Tuyen Hoa District','tuyen_hoa','44'),
('454',N'Quảng Trạch',N'Quang Trach',N'Huyện Quảng Trạch',N'Quang Trach District','quang_trach','44'),
('455',N'Bố Trạch',N'Bo Trach',N'Huyện Bố Trạch',N'Bo Trach District','bo_trach','44'),
('456',N'Quảng Ninh',N'Quang Ninh',N'Huyện Quảng Ninh',N'Quang Ninh District','quang_ninh','44'),
('457',N'Lệ Thủy',N'Le Thuy',N'Huyện Lệ Thủy',N'Le Thuy District','le_thuy','44'),
('458',N'Ba Đồn',N'Ba Don',N'Thị xã Ba Đồn',N'Ba Don Town','ba_don','44'),
('461',N'Đông Hà',N'Dong Ha',N'Thành phố Đông Hà',N'Dong Ha City','dong_ha','45'),
('462',N'Quảng Trị',N'Quang Tri',N'Thị xã Quảng Trị',N'Quang Tri Town','quang_tri','45'),
('464',N'Vĩnh Linh',N'Vinh Linh',N'Huyện Vĩnh Linh',N'Vinh Linh District','vinh_linh','45'),
('465',N'Hướng Hóa',N'Huong Hoa',N'Huyện Hướng Hóa',N'Huong Hoa District','huong_hoa','45'),
('466',N'Gio Linh',N'Gio Linh',N'Huyện Gio Linh',N'Gio Linh District','gio_linh','45'),
('467',N'Đa Krông',N'Da Krong',N'Huyện Đa Krông',N'Da Krong District','da_krong','45'),
('468',N'Cam Lộ',N'Cam Lo',N'Huyện Cam Lộ',N'Cam Lo District','cam_lo','45'),
('469',N'Triệu Phong',N'Trieu Phong',N'Huyện Triệu Phong',N'Trieu Phong District','trieu_phong','45'),
('470',N'Hải Lăng',N'Hai Lang',N'Huyện Hải Lăng',N'Hai Lang District','hai_lang','45'),
('474',N'Huế',N'Hue',N'Thành phố Huế',N'Hue City','hue','46'),
('476',N'Phong Điền',N'Phong Dien',N'Huyện Phong Điền',N'Phong Dien District','phong_dien','46'),
('477',N'Quảng Điền',N'Quang Dien',N'Huyện Quảng Điền',N'Quang Dien District','quang_dien','46'),
('478',N'Phú Vang',N'Phu Vang',N'Huyện Phú Vang',N'Phu Vang District','phu_vang','46'),
('479',N'Hương Thủy',N'Huong Thuy',N'Thị xã Hương Thủy',N'Huong Thuy Town','huong_thuy','46'),
('480',N'Hương Trà',N'Huong Tra',N'Thị xã Hương Trà',N'Huong Tra Town','huong_tra','46'),
('481',N'A Lưới',N'A Luoi',N'Huyện A Lưới',N'A Luoi District','a_luoi','46'),
('482',N'Phú Lộc',N'Phu Loc',N'Huyện Phú Lộc',N'Phu Loc District','phu_loc','46');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('483',N'Nam Đông',N'Nam Dong',N'Huyện Nam Đông',N'Nam Dong District','nam_dong','46'),
('490',N'Liên Chiểu',N'Lien Chieu',N'Quận Liên Chiểu',N'Lien Chieu District','lien_chieu','48'),
('491',N'Thanh Khê',N'Thanh Khe',N'Quận Thanh Khê',N'Thanh Khe District','thanh_khe','48'),
('492',N'Hải Châu',N'Hai Chau',N'Quận Hải Châu',N'Hai Chau District','hai_chau','48'),
('493',N'Sơn Trà',N'Son Tra',N'Quận Sơn Trà',N'Son Tra District','son_tra','48'),
('494',N'Ngũ Hành Sơn',N'Ngu Hanh Son',N'Quận Ngũ Hành Sơn',N'Ngu Hanh Son District','ngu_hanh_son','48'),
('495',N'Cẩm Lệ',N'Cam Le',N'Quận Cẩm Lệ',N'Cam Le District','cam_le','48'),
('497',N'Hòa Vang',N'Hoa Vang',N'Huyện Hòa Vang',N'Hoa Vang District','hoa_vang','48'),
('502',N'Tam Kỳ',N'Tam Ky',N'Thành phố Tam Kỳ',N'Tam Ky City','tam_ky','49'),
('503',N'Hội An',N'Hoi An',N'Thành phố Hội An',N'Hoi An City','hoi_an','49'),
('504',N'Tây Giang',N'Tay Giang',N'Huyện Tây Giang',N'Tay Giang District','tay_giang','49'),
('505',N'Đông Giang',N'Dong Giang',N'Huyện Đông Giang',N'Dong Giang District','dong_giang','49'),
('506',N'Đại Lộc',N'Dai Loc',N'Huyện Đại Lộc',N'Dai Loc District','dai_loc','49'),
('507',N'Điện Bàn',N'Dien Ban',N'Thị xã Điện Bàn',N'Dien Ban Town','dien_ban','49'),
('508',N'Duy Xuyên',N'Duy Xuyen',N'Huyện Duy Xuyên',N'Duy Xuyen District','duy_xuyen','49'),
('509',N'Quế Sơn',N'Que Son',N'Huyện Quế Sơn',N'Que Son District','que_son','49'),
('510',N'Nam Giang',N'Nam Giang',N'Huyện Nam Giang',N'Nam Giang District','nam_giang','49'),
('511',N'Phước Sơn',N'Phuoc Son',N'Huyện Phước Sơn',N'Phuoc Son District','phuoc_son','49'),
('512',N'Hiệp Đức',N'Hiep Duc',N'Huyện Hiệp Đức',N'Hiep Duc District','hiep_duc','49'),
('513',N'Thăng Bình',N'Thang Binh',N'Huyện Thăng Bình',N'Thang Binh District','thang_binh','49'),
('514',N'Tiên Phước',N'Tien Phuoc',N'Huyện Tiên Phước',N'Tien Phuoc District','tien_phuoc','49'),
('515',N'Bắc Trà My',N'Bac Tra My',N'Huyện Bắc Trà My',N'Bac Tra My District','bac_tra_my','49'),
('516',N'Nam Trà My',N'Nam Tra My',N'Huyện Nam Trà My',N'Nam Tra My District','nam_tra_my','49'),
('517',N'Núi Thành',N'Nui Thanh',N'Huyện Núi Thành',N'Nui Thanh District','nui_thanh','49'),
('518',N'Phú Ninh',N'Phu Ninh',N'Huyện Phú Ninh',N'Phu Ninh District','phu_ninh','49'),
('519',N'Nông Sơn',N'Nong Son',N'Huyện Nông Sơn',N'Nong Son District','nong_son','49'),
('522',N'Quảng Ngãi',N'Quang Ngai',N'Thành phố Quảng Ngãi',N'Quang Ngai City','quang_ngai','51'),
('524',N'Bình Sơn',N'Binh Son',N'Huyện Bình Sơn',N'Binh Son District','binh_son','51'),
('525',N'Trà Bồng',N'Tra Bong',N'Huyện Trà Bồng',N'Tra Bong District','tra_bong','51'),
('527',N'Sơn Tịnh',N'Son Tinh',N'Huyện Sơn Tịnh',N'Son Tinh District','son_tinh','51'),
('528',N'Tư Nghĩa',N'Tu Nghia',N'Huyện Tư Nghĩa',N'Tu Nghia District','tu_nghia','51'),
('529',N'Sơn Hà',N'Son Ha',N'Huyện Sơn Hà',N'Son Ha District','son_ha','51'),
('530',N'Sơn Tây',N'Son Tay',N'Huyện Sơn Tây',N'Son Tay District','son_tay','51'),
('531',N'Minh Long',N'Minh Long',N'Huyện Minh Long',N'Minh Long District','minh_long','51'),
('532',N'Nghĩa Hành',N'Nghia Hanh',N'Huyện Nghĩa Hành',N'Nghia Hanh District','nghia_hanh','51'),
('533',N'Mộ Đức',N'Mo Duc',N'Huyện Mộ Đức',N'Mo Duc District','mo_duc','51'),
('534',N'Đức Phổ',N'Duc Pho',N'Thị xã Đức Phổ',N'Duc Pho Town','duc_pho','51'),
('535',N'Ba Tơ',N'Ba To',N'Huyện Ba Tơ',N'Ba To District','ba_to','51'),
('540',N'Quy Nhơn',N'Quy Nhon',N'Thành phố Quy Nhơn',N'Quy Nhon City','quy_nhon','52'),
('542',N'An Lão',N'An Lao',N'Huyện An Lão',N'An Lao District','an_lao','52'),
('543',N'Hoài Nhơn',N'Hoai Nhon',N'Thị xã Hoài Nhơn',N'Hoai Nhon Town','hoai_nhon','52'),
('544',N'Hoài Ân',N'Hoai An',N'Huyện Hoài Ân',N'Hoai An District','hoai_an','52'),
('545',N'Phù Mỹ',N'Phu My',N'Huyện Phù Mỹ',N'Phu My District','phu_my','52'),
('546',N'Vĩnh Thạnh',N'Vinh Thanh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh District','vinh_thanh','52'),
('547',N'Tây Sơn',N'Tay Son',N'Huyện Tây Sơn',N'Tay Son District','tay_son','52'),
('548',N'Phù Cát',N'Phu Cat',N'Huyện Phù Cát',N'Phu Cat District','phu_cat','52'),
('549',N'An Nhơn',N'An Nhon',N'Thị xã An Nhơn',N'An Nhon Town','an_nhon','52'),
('550',N'Tuy Phước',N'Tuy Phuoc',N'Huyện Tuy Phước',N'Tuy Phuoc District','tuy_phuoc','52'),
('551',N'Vân Canh',N'Van Canh',N'Huyện Vân Canh',N'Van Canh District','van_canh','52'),
('555',N'Tuy Hoà',N'Tuy Hoa',N'Thành phố Tuy Hoà',N'Tuy Hoa City','tuy_hoa','54');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('557',N'Sông Cầu',N'Song Cau',N'Thị xã Sông Cầu',N'Song Cau Town','song_cau','54'),
('558',N'Đồng Xuân',N'Dong Xuan',N'Huyện Đồng Xuân',N'Dong Xuan District','dong_xuan','54'),
('559',N'Tuy An',N'Tuy An',N'Huyện Tuy An',N'Tuy An District','tuy_an','54'),
('560',N'Sơn Hòa',N'Son Hoa',N'Huyện Sơn Hòa',N'Son Hoa District','son_hoa','54'),
('561',N'Sông Hinh',N'Song Hinh',N'Huyện Sông Hinh',N'Song Hinh District','song_hinh','54'),
('562',N'Tây Hoà',N'Tay Hoa',N'Huyện Tây Hoà',N'Tay Hoa District','tay_hoa','54'),
('563',N'Phú Hoà',N'Phu Hoa',N'Huyện Phú Hoà',N'Phu Hoa District','phu_hoa','54'),
('564',N'Đông Hòa',N'Dong Hoa',N'Thị xã Đông Hòa',N'Dong Hoa Town','dong_hoa','54'),
('568',N'Nha Trang',N'Nha Trang',N'Thành phố Nha Trang',N'Nha Trang City','nha_trang','56'),
('569',N'Cam Ranh',N'Cam Ranh',N'Thành phố Cam Ranh',N'Cam Ranh City','cam_ranh','56'),
('570',N'Cam Lâm',N'Cam Lam',N'Huyện Cam Lâm',N'Cam Lam District','cam_lam','56'),
('571',N'Vạn Ninh',N'Van Ninh',N'Huyện Vạn Ninh',N'Van Ninh District','van_ninh','56'),
('572',N'Ninh Hòa',N'Ninh Hoa',N'Thị xã Ninh Hòa',N'Ninh Hoa Town','ninh_hoa','56'),
('573',N'Khánh Vĩnh',N'Khanh Vinh',N'Huyện Khánh Vĩnh',N'Khanh Vinh District','khanh_vinh','56'),
('574',N'Diên Khánh',N'Dien Khanh',N'Huyện Diên Khánh',N'Dien Khanh District','dien_khanh','56'),
('575',N'Khánh Sơn',N'Khanh Son',N'Huyện Khánh Sơn',N'Khanh Son District','khanh_son','56'),
('576',N'Trường Sa',N'Truong Sa',N'Huyện Trường Sa',N'Truong Sa District','truong_sa','56'),
('582',N'Phan Rang-Tháp Chàm',N'Phan Rang-Thap Cham',N'Thành phố Phan Rang-Tháp Chàm',N'Phan Rang-Thap Cham City','phan_rang-thap_cham','58'),
('584',N'Bác Ái',N'Bac Ai',N'Huyện Bác Ái',N'Bac Ai District','bac_ai','58'),
('585',N'Ninh Sơn',N'Ninh Son',N'Huyện Ninh Sơn',N'Ninh Son District','ninh_son','58'),
('586',N'Ninh Hải',N'Ninh Hai',N'Huyện Ninh Hải',N'Ninh Hai District','ninh_hai','58'),
('587',N'Ninh Phước',N'Ninh Phuoc',N'Huyện Ninh Phước',N'Ninh Phuoc District','ninh_phuoc','58'),
('588',N'Thuận Bắc',N'Thuan Bac',N'Huyện Thuận Bắc',N'Thuan Bac District','thuan_bac','58'),
('589',N'Thuận Nam',N'Thuan Nam',N'Huyện Thuận Nam',N'Thuan Nam District','thuan_nam','58'),
('593',N'Phan Thiết',N'Phan Thiet',N'Thành phố Phan Thiết',N'Phan Thiet City','phan_thiet','60'),
('594',N'La Gi',N'La Gi',N'Thị xã La Gi',N'La Gi Town','la_gi','60'),
('595',N'Tuy Phong',N'Tuy Phong',N'Huyện Tuy Phong',N'Tuy Phong District','tuy_phong','60'),
('596',N'Bắc Bình',N'Bac Binh',N'Huyện Bắc Bình',N'Bac Binh District','bac_binh','60'),
('597',N'Hàm Thuận Bắc',N'Ham Thuan Bac',N'Huyện Hàm Thuận Bắc',N'Ham Thuan Bac District','ham_thuan_bac','60'),
('598',N'Hàm Thuận Nam',N'Ham Thuan Nam',N'Huyện Hàm Thuận Nam',N'Ham Thuan Nam District','ham_thuan_nam','60'),
('599',N'Tánh Linh',N'Tanh Linh',N'Huyện Tánh Linh',N'Tanh Linh District','tanh_linh','60'),
('600',N'Đức Linh',N'Duc Linh',N'Huyện Đức Linh',N'Duc Linh District','duc_linh','60'),
('601',N'Hàm Tân',N'Ham Tan',N'Huyện Hàm Tân',N'Ham Tan District','ham_tan','60'),
('602',N'Phú Quí',N'Phu Qui',N'Huyện Phú Quí',N'Phu Qui District','phu_qui','60'),
('608',N'Kon Tum',N'Kon Tum',N'Thành phố Kon Tum',N'Kon Tum City','kon_tum','62'),
('610',N'Đắk Glei',N'Dak Glei',N'Huyện Đắk Glei',N'Dak Glei District','dak_glei','62'),
('611',N'Ngọc Hồi',N'Ngoc Hoi',N'Huyện Ngọc Hồi',N'Ngoc Hoi District','ngoc_hoi','62'),
('612',N'Đắk Tô',N'Dak To',N'Huyện Đắk Tô',N'Dak To District','dak_to','62'),
('613',N'Kon Plông',N'Kon Plong',N'Huyện Kon Plông',N'Kon Plong District','kon_plong','62'),
('614',N'Kon Rẫy',N'Kon Ray',N'Huyện Kon Rẫy',N'Kon Ray District','kon_ray','62'),
('615',N'Đắk Hà',N'Dak Ha',N'Huyện Đắk Hà',N'Dak Ha District','dak_ha','62'),
('616',N'Sa Thầy',N'Sa Thay',N'Huyện Sa Thầy',N'Sa Thay District','sa_thay','62'),
('617',N'Tu Mơ Rông',N'Tu Mo Rong',N'Huyện Tu Mơ Rông',N'Tu Mo Rong District','tu_mo_rong','62'),
('618',N'Ia H'' Drai',N'Ia H'' Drai',N'Huyện Ia H'' Drai',N'Ia H'' Drai District','ia_h_drai','62'),
('622',N'Pleiku',N'Pleiku',N'Thành phố Pleiku',N'Pleiku City','pleiku','64'),
('623',N'An Khê',N'An Khe',N'Thị xã An Khê',N'An Khe Town','an_khe','64'),
('624',N'Ayun Pa',N'Ayun Pa',N'Thị xã Ayun Pa',N'Ayun Pa Town','ayun_pa','64'),
('625',N'KBang',N'KBang',N'Huyện KBang',N'KBang District','kbang','64'),
('626',N'Đăk Đoa',N'Dak Doa',N'Huyện Đăk Đoa',N'Dak Doa District','dak_doa','64'),
('627',N'Chư Păh',N'Chu Pah',N'Huyện Chư Păh',N'Chu Pah District','chu_pah','64');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('628',N'Ia Grai',N'Ia Grai',N'Huyện Ia Grai',N'Ia Grai District','ia_grai','64'),
('629',N'Mang Yang',N'Mang Yang',N'Huyện Mang Yang',N'Mang Yang District','mang_yang','64'),
('630',N'Kông Chro',N'Kong Chro',N'Huyện Kông Chro',N'Kong Chro District','kong_chro','64'),
('631',N'Đức Cơ',N'Duc Co',N'Huyện Đức Cơ',N'Duc Co District','duc_co','64'),
('632',N'Chư Prông',N'Chu Prong',N'Huyện Chư Prông',N'Chu Prong District','chu_prong','64'),
('633',N'Chư Sê',N'Chu Se',N'Huyện Chư Sê',N'Chu Se District','chu_se','64'),
('634',N'Đăk Pơ',N'Dak Po',N'Huyện Đăk Pơ',N'Dak Po District','dak_po','64'),
('635',N'Ia Pa',N'Ia Pa',N'Huyện Ia Pa',N'Ia Pa District','ia_pa','64'),
('637',N'Krông Pa',N'Krong Pa',N'Huyện Krông Pa',N'Krong Pa District','krong_pa','64'),
('638',N'Phú Thiện',N'Phu Thien',N'Huyện Phú Thiện',N'Phu Thien District','phu_thien','64'),
('639',N'Chư Pưh',N'Chu Puh',N'Huyện Chư Pưh',N'Chu Puh District','chu_puh','64'),
('643',N'Buôn Ma Thuột',N'Buon Ma Thuot',N'Thành phố Buôn Ma Thuột',N'Buon Ma Thuot City','buon_ma_thuot','66'),
('644',N'Buôn Hồ',N'Buon Ho',N'Thị xã Buôn Hồ',N'Buon Ho Town','buon_ho','66'),
('645',N'Ea H''leo',N'Ea H''leo',N'Huyện Ea H''leo',N'Ea H''leo District','ea_hleo','66'),
('646',N'Ea Súp',N'Ea Sup',N'Huyện Ea Súp',N'Ea Sup District','ea_sup','66'),
('647',N'Buôn Đôn',N'Buon Don',N'Huyện Buôn Đôn',N'Buon Don District','buon_don','66'),
('648',N'Cư M''gar',N'Cu M''gar',N'Huyện Cư M''gar',N'Cu M''gar District','cu_mgar','66'),
('649',N'Krông Búk',N'Krong Buk',N'Huyện Krông Búk',N'Krong Buk District','krong_buk','66'),
('650',N'Krông Năng',N'Krong Nang',N'Huyện Krông Năng',N'Krong Nang District','krong_nang','66'),
('651',N'Ea Kar',N'Ea Kar',N'Huyện Ea Kar',N'Ea Kar District','ea_kar','66'),
('652',N'M''Đrắk',N'M''Drak',N'Huyện M''Đrắk',N'M''Drak District','mdrak','66'),
('653',N'Krông Bông',N'Krong Bong',N'Huyện Krông Bông',N'Krong Bong District','krong_bong','66'),
('654',N'Krông Pắc',N'Krong Pac',N'Huyện Krông Pắc',N'Krong Pac District','krong_pac','66'),
('655',N'Krông A Na',N'Krong A Na',N'Huyện Krông A Na',N'Krong A Na District','krong_a_na','66'),
('656',N'Lắk',N'Lak',N'Huyện Lắk',N'Lak District','lak','66'),
('657',N'Cư Kuin',N'Cu Kuin',N'Huyện Cư Kuin',N'Cu Kuin District','cu_kuin','66'),
('660',N'Gia Nghĩa',N'Gia Nghia',N'Thành phố Gia Nghĩa',N'Gia Nghia City','gia_nghia','67'),
('661',N'Đăk Glong',N'Dak Glong',N'Huyện Đăk Glong',N'Dak Glong District','dak_glong','67'),
('662',N'Cư Jút',N'Cu Jut',N'Huyện Cư Jút',N'Cu Jut District','cu_jut','67'),
('663',N'Đắk Mil',N'Dak Mil',N'Huyện Đắk Mil',N'Dak Mil District','dak_mil','67'),
('664',N'Krông Nô',N'Krong No',N'Huyện Krông Nô',N'Krong No District','krong_no','67'),
('665',N'Đắk Song',N'Dak Song',N'Huyện Đắk Song',N'Dak Song District','dak_song','67'),
('666',N'Đắk R''Lấp',N'Dak R''Lap',N'Huyện Đắk R''Lấp',N'Dak R''Lap District','dak_rlap','67'),
('667',N'Tuy Đức',N'Tuy Duc',N'Huyện Tuy Đức',N'Tuy Duc District','tuy_duc','67'),
('672',N'Đà Lạt',N'Da Lat',N'Thành phố Đà Lạt',N'Da Lat City','da_lat','68'),
('673',N'Bảo Lộc',N'Bao Loc',N'Thành phố Bảo Lộc',N'Bao Loc City','bao_loc','68'),
('674',N'Đam Rông',N'Dam Rong',N'Huyện Đam Rông',N'Dam Rong District','dam_rong','68'),
('675',N'Lạc Dương',N'Lac Duong',N'Huyện Lạc Dương',N'Lac Duong District','lac_duong','68'),
('676',N'Lâm Hà',N'Lam Ha',N'Huyện Lâm Hà',N'Lam Ha District','lam_ha','68'),
('677',N'Đơn Dương',N'Don Duong',N'Huyện Đơn Dương',N'Don Duong District','don_duong','68'),
('678',N'Đức Trọng',N'Duc Trong',N'Huyện Đức Trọng',N'Duc Trong District','duc_trong','68'),
('679',N'Di Linh',N'Di Linh',N'Huyện Di Linh',N'Di Linh District','di_linh','68'),
('680',N'Bảo Lâm',N'Bao Lam',N'Huyện Bảo Lâm',N'Bao Lam District','bao_lam','68'),
('681',N'Đạ Huoai',N'Da Huoai',N'Huyện Đạ Huoai',N'Da Huoai District','da_huoai','68'),
('682',N'Đạ Tẻh',N'Da Teh',N'Huyện Đạ Tẻh',N'Da Teh District','da_teh','68'),
('683',N'Cát Tiên',N'Cat Tien',N'Huyện Cát Tiên',N'Cat Tien District','cat_tien','68'),
('688',N'Phước Long',N'Phuoc Long',N'Thị xã Phước Long',N'Phuoc Long Town','phuoc_long','70'),
('689',N'Đồng Xoài',N'Dong Xoai',N'Thành phố Đồng Xoài',N'Dong Xoai City','dong_xoai','70'),
('690',N'Bình Long',N'Binh Long',N'Thị xã Bình Long',N'Binh Long Town','binh_long','70'),
('691',N'Bù Gia Mập',N'Bu Gia Map',N'Huyện Bù Gia Mập',N'Bu Gia Map District','bu_gia_map','70');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('692',N'Lộc Ninh',N'Loc Ninh',N'Huyện Lộc Ninh',N'Loc Ninh District','loc_ninh','70'),
('693',N'Bù Đốp',N'Bu Dop',N'Huyện Bù Đốp',N'Bu Dop District','bu_dop','70'),
('694',N'Hớn Quản',N'Hon Quan',N'Huyện Hớn Quản',N'Hon Quan District','hon_quan','70'),
('695',N'Đồng Phú',N'Dong Phu',N'Huyện Đồng Phú',N'Dong Phu District','dong_phu','70'),
('696',N'Bù Đăng',N'Bu Dang',N'Huyện Bù Đăng',N'Bu Dang District','bu_dang','70'),
('697',N'Chơn Thành',N'Chon Thanh',N'Thị xã Chơn Thành',N'Chon Thanh Town','chon_thanh','70'),
('698',N'Phú Riềng',N'Phu Rieng',N'Huyện Phú Riềng',N'Phu Rieng District','phu_rieng','70'),
('703',N'Tây Ninh',N'Tay Ninh',N'Thành phố Tây Ninh',N'Tay Ninh City','tay_ninh','72'),
('705',N'Tân Biên',N'Tan Bien',N'Huyện Tân Biên',N'Tan Bien District','tan_bien','72'),
('706',N'Tân Châu',N'Tan Chau',N'Huyện Tân Châu',N'Tan Chau District','tan_chau','72'),
('707',N'Dương Minh Châu',N'Duong Minh Chau',N'Huyện Dương Minh Châu',N'Duong Minh Chau District','duong_minh_chau','72'),
('708',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','72'),
('709',N'Hòa Thành',N'Hoa Thanh',N'Thị xã Hòa Thành',N'Hoa Thanh Town','hoa_thanh','72'),
('710',N'Gò Dầu',N'Go Dau',N'Huyện Gò Dầu',N'Go Dau District','go_dau','72'),
('711',N'Bến Cầu',N'Ben Cau',N'Huyện Bến Cầu',N'Ben Cau District','ben_cau','72'),
('712',N'Trảng Bàng',N'Trang Bang',N'Thị xã Trảng Bàng',N'Trang Bang Town','trang_bang','72'),
('718',N'Thủ Dầu Một',N'Thu Dau Mot',N'Thành phố Thủ Dầu Một',N'Thu Dau Mot City','thu_dau_mot','74'),
('719',N'Bàu Bàng',N'Bau Bang',N'Huyện Bàu Bàng',N'Bau Bang District','bau_bang','74'),
('720',N'Dầu Tiếng',N'Dau Tieng',N'Huyện Dầu Tiếng',N'Dau Tieng District','dau_tieng','74'),
('721',N'Bến Cát',N'Ben Cat',N'Thành phố Bến Cát',N'Ben Cat City','ben_cat','74'),
('722',N'Phú Giáo',N'Phu Giao',N'Huyện Phú Giáo',N'Phu Giao District','phu_giao','74'),
('723',N'Tân Uyên',N'Tan Uyen',N'Thành phố Tân Uyên',N'Tan Uyen City','tan_uyen','74'),
('724',N'Dĩ An',N'Di An',N'Thành phố Dĩ An',N'Di An City','di_an','74'),
('725',N'Thuận An',N'Thuan An',N'Thành phố Thuận An',N'Thuan An City','thuan_an','74'),
('726',N'Bắc Tân Uyên',N'Bac Tan Uyen',N'Huyện Bắc Tân Uyên',N'Bac Tan Uyen District','bac_tan_uyen','74'),
('731',N'Biên Hòa',N'Bien Hoa',N'Thành phố Biên Hòa',N'Bien Hoa City','bien_hoa','75'),
('732',N'Long Khánh',N'Long Khanh',N'Thành phố Long Khánh',N'Long Khanh City','long_khanh','75'),
('734',N'Tân Phú',N'Tan Phu',N'Huyện Tân Phú',N'Tan Phu District','tan_phu','75'),
('735',N'Vĩnh Cửu',N'Vinh Cuu',N'Huyện Vĩnh Cửu',N'Vinh Cuu District','vinh_cuu','75'),
('736',N'Định Quán',N'Dinh Quan',N'Huyện Định Quán',N'Dinh Quan District','dinh_quan','75'),
('737',N'Trảng Bom',N'Trang Bom',N'Huyện Trảng Bom',N'Trang Bom District','trang_bom','75'),
('738',N'Thống Nhất',N'Thong Nhat',N'Huyện Thống Nhất',N'Thong Nhat District','thong_nhat','75'),
('739',N'Cẩm Mỹ',N'Cam My',N'Huyện Cẩm Mỹ',N'Cam My District','cam_my','75'),
('740',N'Long Thành',N'Long Thanh',N'Huyện Long Thành',N'Long Thanh District','long_thanh','75'),
('741',N'Xuân Lộc',N'Xuan Loc',N'Huyện Xuân Lộc',N'Xuan Loc District','xuan_loc','75'),
('742',N'Nhơn Trạch',N'Nhon Trach',N'Huyện Nhơn Trạch',N'Nhon Trach District','nhon_trach','75'),
('747',N'Vũng Tàu',N'Vung Tau',N'Thành phố Vũng Tàu',N'Vung Tau City','vung_tau','77'),
('748',N'Bà Rịa',N'Ba Ria',N'Thành phố Bà Rịa',N'Ba Ria City','ba_ria','77'),
('750',N'Châu Đức',N'Chau Duc',N'Huyện Châu Đức',N'Chau Duc District','chau_duc','77'),
('751',N'Xuyên Mộc',N'Xuyen Moc',N'Huyện Xuyên Mộc',N'Xuyen Moc District','xuyen_moc','77'),
('752',N'Long Điền',N'Long Dien',N'Huyện Long Điền',N'Long Dien District','long_dien','77'),
('753',N'Đất Đỏ',N'Dat Do',N'Huyện Đất Đỏ',N'Dat Do District','dat_do','77'),
('754',N'Phú Mỹ',N'Phu My',N'Thị xã Phú Mỹ',N'Phu My Town','phu_my','77'),
('760',N'1',N'1',N'Quận 1',N'District 1','1','79'),
('761',N'12',N'12',N'Quận 12',N'District 12','12','79'),
('764',N'Gò Vấp',N'Go Vap',N'Quận Gò Vấp',N'Go Vap District','go_vap','79'),
('765',N'Bình Thạnh',N'Binh Thanh',N'Quận Bình Thạnh',N'Binh Thanh District','binh_thanh','79'),
('766',N'Tân Bình',N'Tan Binh',N'Quận Tân Bình',N'Tan Binh District','tan_binh','79'),
('767',N'Tân Phú',N'Tan Phu',N'Quận Tân Phú',N'Tan Phu District','tan_phu','79'),
('768',N'Phú Nhuận',N'Phu Nhuan',N'Quận Phú Nhuận',N'Phu Nhuan District','phu_nhuan','79');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('769',N'Thủ Đức',N'Thu Duc',N'Thành phố Thủ Đức',N'Thu Duc City','thu_duc','79'),
('770',N'3',N'3',N'Quận 3',N'District 3','3','79'),
('771',N'10',N'10',N'Quận 10',N'District 10','10','79'),
('772',N'11',N'11',N'Quận 11',N'District 11','11','79'),
('773',N'4',N'4',N'Quận 4',N'District 4','4','79'),
('774',N'5',N'5',N'Quận 5',N'District 5','5','79'),
('775',N'6',N'6',N'Quận 6',N'District 6','6','79'),
('776',N'8',N'8',N'Quận 8',N'District 8','8','79'),
('777',N'Bình Tân',N'Binh Tan',N'Quận Bình Tân',N'Binh Tan District','binh_tan','79'),
('778',N'7',N'7',N'Quận 7',N'District 7','7','79'),
('783',N'Củ Chi',N'Cu Chi',N'Huyện Củ Chi',N'Cu Chi District','cu_chi','79'),
('784',N'Hóc Môn',N'Hoc Mon',N'Huyện Hóc Môn',N'Hoc Mon District','hoc_mon','79'),
('785',N'Bình Chánh',N'Binh Chanh',N'Huyện Bình Chánh',N'Binh Chanh District','binh_chanh','79'),
('786',N'Nhà Bè',N'Nha Be',N'Huyện Nhà Bè',N'Nha Be District','nha_be','79'),
('787',N'Cần Giờ',N'Can Gio',N'Huyện Cần Giờ',N'Can Gio District','can_gio','79'),
('794',N'Tân An',N'Tan An',N'Thành phố Tân An',N'Tan An City','tan_an','80'),
('795',N'Kiến Tường',N'Kien Tuong',N'Thị xã Kiến Tường',N'Kien Tuong Town','kien_tuong','80'),
('796',N'Tân Hưng',N'Tan Hung',N'Huyện Tân Hưng',N'Tan Hung District','tan_hung','80'),
('797',N'Vĩnh Hưng',N'Vinh Hung',N'Huyện Vĩnh Hưng',N'Vinh Hung District','vinh_hung','80'),
('798',N'Mộc Hóa',N'Moc Hoa',N'Huyện Mộc Hóa',N'Moc Hoa District','moc_hoa','80'),
('799',N'Tân Thạnh',N'Tan Thanh',N'Huyện Tân Thạnh',N'Tan Thanh District','tan_thanh','80'),
('800',N'Thạnh Hóa',N'Thanh Hoa',N'Huyện Thạnh Hóa',N'Thanh Hoa District','thanh_hoa','80'),
('801',N'Đức Huệ',N'Duc Hue',N'Huyện Đức Huệ',N'Duc Hue District','duc_hue','80'),
('802',N'Đức Hòa',N'Duc Hoa',N'Huyện Đức Hòa',N'Duc Hoa District','duc_hoa','80'),
('803',N'Bến Lức',N'Ben Luc',N'Huyện Bến Lức',N'Ben Luc District','ben_luc','80'),
('804',N'Thủ Thừa',N'Thu Thua',N'Huyện Thủ Thừa',N'Thu Thua District','thu_thua','80'),
('805',N'Tân Trụ',N'Tan Tru',N'Huyện Tân Trụ',N'Tan Tru District','tan_tru','80'),
('806',N'Cần Đước',N'Can Duoc',N'Huyện Cần Đước',N'Can Duoc District','can_duoc','80'),
('807',N'Cần Giuộc',N'Can Giuoc',N'Huyện Cần Giuộc',N'Can Giuoc District','can_giuoc','80'),
('808',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','80'),
('815',N'Mỹ Tho',N'My Tho',N'Thành phố Mỹ Tho',N'My Tho City','my_tho','82'),
('816',N'Gò Công',N'Go Cong',N'Thành phố Gò Công',N'Go Cong City','go_cong','82'),
('817',N'Cai Lậy',N'Cai Lay',N'Thị xã Cai Lậy',N'Cai Lay Town','cai_lay','82'),
('818',N'Tân Phước',N'Tan Phuoc',N'Huyện Tân Phước',N'Tan Phuoc District','tan_phuoc','82'),
('819',N'Cái Bè',N'Cai Be',N'Huyện Cái Bè',N'Cai Be District','cai_be','82'),
('820',N'Cai Lậy',N'Cai Lay',N'Huyện Cai Lậy',N'Cai Lay District','cai_lay','82'),
('821',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','82'),
('822',N'Chợ Gạo',N'Cho Gao',N'Huyện Chợ Gạo',N'Cho Gao District','cho_gao','82'),
('823',N'Gò Công Tây',N'Go Cong Tay',N'Huyện Gò Công Tây',N'Go Cong Tay District','go_cong_tay','82'),
('824',N'Gò Công Đông',N'Go Cong Dong',N'Huyện Gò Công Đông',N'Go Cong Dong District','go_cong_dong','82'),
('825',N'Tân Phú Đông',N'Tan Phu Dong',N'Huyện Tân Phú Đông',N'Tan Phu Dong District','tan_phu_dong','82'),
('829',N'Bến Tre',N'Ben Tre',N'Thành phố Bến Tre',N'Ben Tre City','ben_tre','83'),
('831',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','83'),
('832',N'Chợ Lách',N'Cho Lach',N'Huyện Chợ Lách',N'Cho Lach District','cho_lach','83'),
('833',N'Mỏ Cày Nam',N'Mo Cay Nam',N'Huyện Mỏ Cày Nam',N'Mo Cay Nam District','mo_cay_nam','83'),
('834',N'Giồng Trôm',N'Giong Trom',N'Huyện Giồng Trôm',N'Giong Trom District','giong_trom','83'),
('835',N'Bình Đại',N'Binh Dai',N'Huyện Bình Đại',N'Binh Dai District','binh_dai','83'),
('836',N'Ba Tri',N'Ba Tri',N'Huyện Ba Tri',N'Ba Tri District','ba_tri','83'),
('837',N'Thạnh Phú',N'Thanh Phu',N'Huyện Thạnh Phú',N'Thanh Phu District','thanh_phu','83'),
('838',N'Mỏ Cày Bắc',N'Mo Cay Bac',N'Huyện Mỏ Cày Bắc',N'Mo Cay Bac District','mo_cay_bac','83');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('842',N'Trà Vinh',N'Tra Vinh',N'Thành phố Trà Vinh',N'Tra Vinh City','tra_vinh','84'),
('844',N'Càng Long',N'Cang Long',N'Huyện Càng Long',N'Cang Long District','cang_long','84'),
('845',N'Cầu Kè',N'Cau Ke',N'Huyện Cầu Kè',N'Cau Ke District','cau_ke','84'),
('846',N'Tiểu Cần',N'Tieu Can',N'Huyện Tiểu Cần',N'Tieu Can District','tieu_can','84'),
('847',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','84'),
('848',N'Cầu Ngang',N'Cau Ngang',N'Huyện Cầu Ngang',N'Cau Ngang District','cau_ngang','84'),
('849',N'Trà Cú',N'Tra Cu',N'Huyện Trà Cú',N'Tra Cu District','tra_cu','84'),
('850',N'Duyên Hải',N'Duyen Hai',N'Huyện Duyên Hải',N'Duyen Hai District','duyen_hai','84'),
('851',N'Duyên Hải',N'Duyen Hai',N'Thị xã Duyên Hải',N'Duyen Hai Town','duyen_hai','84'),
('855',N'Vĩnh Long',N'Vinh Long',N'Thành phố Vĩnh Long',N'Vinh Long City','vinh_long','86'),
('857',N'Long Hồ',N'Long Ho',N'Huyện Long Hồ',N'Long Ho District','long_ho','86'),
('858',N'Mang Thít',N'Mang Thit',N'Huyện Mang Thít',N'Mang Thit District','mang_thit','86'),
('859',N'Vũng Liêm',N'Vung Liem',N'Huyện Vũng Liêm',N'Vung Liem District','vung_liem','86'),
('860',N'Tam Bình',N'Tam Binh',N'Huyện Tam Bình',N'Tam Binh District','tam_binh','86'),
('861',N'Bình Minh',N'Binh Minh',N'Thị xã Bình Minh',N'Binh Minh Town','binh_minh','86'),
('862',N'Trà Ôn',N'Tra On',N'Huyện Trà Ôn',N'Tra On District','tra_on','86'),
('863',N'Bình Tân',N'Binh Tan',N'Huyện Bình Tân',N'Binh Tan District','binh_tan','86'),
('866',N'Cao Lãnh',N'Cao Lanh',N'Thành phố Cao Lãnh',N'Cao Lanh City','cao_lanh','87'),
('867',N'Sa Đéc',N'Sa Dec',N'Thành phố Sa Đéc',N'Sa Dec City','sa_dec','87'),
('868',N'Hồng Ngự',N'Hong Ngu',N'Thành phố Hồng Ngự',N'Hong Ngu City','hong_ngu','87'),
('869',N'Tân Hồng',N'Tan Hong',N'Huyện Tân Hồng',N'Tan Hong District','tan_hong','87'),
('870',N'Hồng Ngự',N'Hong Ngu',N'Huyện Hồng Ngự',N'Hong Ngu District','hong_ngu','87'),
('871',N'Tam Nông',N'Tam Nong',N'Huyện Tam Nông',N'Tam Nong District','tam_nong','87'),
('872',N'Tháp Mười',N'Thap Muoi',N'Huyện Tháp Mười',N'Thap Muoi District','thap_muoi','87'),
('873',N'Cao Lãnh',N'Cao Lanh',N'Huyện Cao Lãnh',N'Cao Lanh District','cao_lanh','87'),
('874',N'Thanh Bình',N'Thanh Binh',N'Huyện Thanh Bình',N'Thanh Binh District','thanh_binh','87'),
('875',N'Lấp Vò',N'Lap Vo',N'Huyện Lấp Vò',N'Lap Vo District','lap_vo','87'),
('876',N'Lai Vung',N'Lai Vung',N'Huyện Lai Vung',N'Lai Vung District','lai_vung','87'),
('877',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','87'),
('883',N'Long Xuyên',N'Long Xuyen',N'Thành phố Long Xuyên',N'Long Xuyen City','long_xuyen','89'),
('884',N'Châu Đốc',N'Chau Doc',N'Thành phố Châu Đốc',N'Chau Doc City','chau_doc','89'),
('886',N'An Phú',N'An Phu',N'Huyện An Phú',N'An Phu District','an_phu','89'),
('887',N'Tân Châu',N'Tan Chau',N'Thị xã Tân Châu',N'Tan Chau Town','tan_chau','89'),
('888',N'Phú Tân',N'Phu Tan',N'Huyện Phú Tân',N'Phu Tan District','phu_tan','89'),
('889',N'Châu Phú',N'Chau Phu',N'Huyện Châu Phú',N'Chau Phu District','chau_phu','89'),
('890',N'Tịnh Biên',N'Tinh Bien',N'Thị xã Tịnh Biên',N'Tinh Bien Town','tinh_bien','89'),
('891',N'Tri Tôn',N'Tri Ton',N'Huyện Tri Tôn',N'Tri Ton District','tri_ton','89'),
('892',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','89'),
('893',N'Chợ Mới',N'Cho Moi',N'Huyện Chợ Mới',N'Cho Moi District','cho_moi','89'),
('894',N'Thoại Sơn',N'Thoai Son',N'Huyện Thoại Sơn',N'Thoai Son District','thoai_son','89'),
('899',N'Rạch Giá',N'Rach Gia',N'Thành phố Rạch Giá',N'Rach Gia City','rach_gia','91'),
('900',N'Hà Tiên',N'Ha Tien',N'Thành phố Hà Tiên',N'Ha Tien City','ha_tien','91'),
('902',N'Kiên Lương',N'Kien Luong',N'Huyện Kiên Lương',N'Kien Luong District','kien_luong','91'),
('903',N'Hòn Đất',N'Hon Dat',N'Huyện Hòn Đất',N'Hon Dat District','hon_dat','91'),
('904',N'Tân Hiệp',N'Tan Hiep',N'Huyện Tân Hiệp',N'Tan Hiep District','tan_hiep','91'),
('905',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','91'),
('906',N'Giồng Riềng',N'Giong Rieng',N'Huyện Giồng Riềng',N'Giong Rieng District','giong_rieng','91'),
('907',N'Gò Quao',N'Go Quao',N'Huyện Gò Quao',N'Go Quao District','go_quao','91'),
('908',N'An Biên',N'An Bien',N'Huyện An Biên',N'An Bien District','an_bien','91'),
('909',N'An Minh',N'An Minh',N'Huyện An Minh',N'An Minh District','an_minh','91');

INSERT INTO districts(code,name,name_en,full_name,full_name_en,code_name,province_code) VALUES
('910',N'Vĩnh Thuận',N'Vinh Thuan',N'Huyện Vĩnh Thuận',N'Vinh Thuan District','vinh_thuan','91'),
('911',N'Phú Quốc',N'Phu Quoc',N'Thành phố Phú Quốc',N'Phu Quoc City','phu_quoc','91'),
('912',N'Kiên Hải',N'Kien Hai',N'Huyện Kiên Hải',N'Kien Hai District','kien_hai','91'),
('913',N'U Minh Thượng',N'U Minh Thuong',N'Huyện U Minh Thượng',N'U Minh Thuong District','u_minh_thuong','91'),
('914',N'Giang Thành',N'Giang Thanh',N'Huyện Giang Thành',N'Giang Thanh District','giang_thanh','91'),
('916',N'Ninh Kiều',N'Ninh Kieu',N'Quận Ninh Kiều',N'Ninh Kieu District','ninh_kieu','92'),
('917',N'Ô Môn',N'O Mon',N'Quận Ô Môn',N'O Mon District','o_mon','92'),
('918',N'Bình Thuỷ',N'Binh Thuy',N'Quận Bình Thuỷ',N'Binh Thuy District','binh_thuy','92'),
('919',N'Cái Răng',N'Cai Rang',N'Quận Cái Răng',N'Cai Rang District','cai_rang','92'),
('923',N'Thốt Nốt',N'Thot Not',N'Quận Thốt Nốt',N'Thot Not District','thot_not','92'),
('924',N'Vĩnh Thạnh',N'Vinh Thanh',N'Huyện Vĩnh Thạnh',N'Vinh Thanh District','vinh_thanh','92'),
('925',N'Cờ Đỏ',N'Co Do',N'Huyện Cờ Đỏ',N'Co Do District','co_do','92'),
('926',N'Phong Điền',N'Phong Dien',N'Huyện Phong Điền',N'Phong Dien District','phong_dien','92'),
('927',N'Thới Lai',N'Thoi Lai',N'Huyện Thới Lai',N'Thoi Lai District','thoi_lai','92'),
('930',N'Vị Thanh',N'Vi Thanh',N'Thành phố Vị Thanh',N'Vi Thanh City','vi_thanh','93'),
('931',N'Ngã Bảy',N'Nga Bay',N'Thành phố Ngã Bảy',N'Nga Bay City','nga_bay','93'),
('932',N'Châu Thành A',N'Chau Thanh A',N'Huyện Châu Thành A',N'Chau Thanh A District','chau_thanh_a','93'),
('933',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','93'),
('934',N'Phụng Hiệp',N'Phung Hiep',N'Huyện Phụng Hiệp',N'Phung Hiep District','phung_hiep','93'),
('935',N'Vị Thuỷ',N'Vi Thuy',N'Huyện Vị Thuỷ',N'Vi Thuy District','vi_thuy','93'),
('936',N'Long Mỹ',N'Long My',N'Huyện Long Mỹ',N'Long My District','long_my','93'),
('937',N'Long Mỹ',N'Long My',N'Thị xã Long Mỹ',N'Long My Town','long_my','93'),
('941',N'Sóc Trăng',N'Soc Trang',N'Thành phố Sóc Trăng',N'Soc Trang City','soc_trang','94'),
('942',N'Châu Thành',N'Chau Thanh',N'Huyện Châu Thành',N'Chau Thanh District','chau_thanh','94'),
('943',N'Kế Sách',N'Ke Sach',N'Huyện Kế Sách',N'Ke Sach District','ke_sach','94'),
('944',N'Mỹ Tú',N'My Tu',N'Huyện Mỹ Tú',N'My Tu District','my_tu','94'),
('945',N'Cù Lao Dung',N'Cu Lao Dung',N'Huyện Cù Lao Dung',N'Cu Lao Dung District','cu_lao_dung','94'),
('946',N'Long Phú',N'Long Phu',N'Huyện Long Phú',N'Long Phu District','long_phu','94'),
('947',N'Mỹ Xuyên',N'My Xuyen',N'Huyện Mỹ Xuyên',N'My Xuyen District','my_xuyen','94'),
('948',N'Ngã Năm',N'Nga Nam',N'Thị xã Ngã Năm',N'Nga Nam Town','nga_nam','94'),
('949',N'Thạnh Trị',N'Thanh Tri',N'Huyện Thạnh Trị',N'Thanh Tri District','thanh_tri','94'),
('950',N'Vĩnh Châu',N'Vinh Chau',N'Thị xã Vĩnh Châu',N'Vinh Chau Town','vinh_chau','94'),
('951',N'Trần Đề',N'Tran De',N'Huyện Trần Đề',N'Tran De District','tran_de','94'),
('954',N'Bạc Liêu',N'Bac Lieu',N'Thành phố Bạc Liêu',N'Bac Lieu City','bac_lieu','95'),
('956',N'Hồng Dân',N'Hong Dan',N'Huyện Hồng Dân',N'Hong Dan District','hong_dan','95'),
('957',N'Phước Long',N'Phuoc Long',N'Huyện Phước Long',N'Phuoc Long District','phuoc_long','95'),
('958',N'Vĩnh Lợi',N'Vinh Loi',N'Huyện Vĩnh Lợi',N'Vinh Loi District','vinh_loi','95'),
('959',N'Giá Rai',N'Gia Rai',N'Thị xã Giá Rai',N'Gia Rai Town','gia_rai','95'),
('960',N'Đông Hải',N'Dong Hai',N'Huyện Đông Hải',N'Dong Hai District','dong_hai','95'),
('961',N'Hoà Bình',N'Hoa Binh',N'Huyện Hoà Bình',N'Hoa Binh District','hoa_binh','95'),
('964',N'Cà Mau',N'Ca Mau',N'Thành phố Cà Mau',N'Ca Mau City','ca_mau','96'),
('966',N'U Minh',N'U Minh',N'Huyện U Minh',N'U Minh District','u_minh','96'),
('967',N'Thới Bình',N'Thoi Binh',N'Huyện Thới Bình',N'Thoi Binh District','thoi_binh','96'),
('968',N'Trần Văn Thời',N'Tran Van Thoi',N'Huyện Trần Văn Thời',N'Tran Van Thoi District','tran_van_thoi','96'),
('969',N'Cái Nước',N'Cai Nuoc',N'Huyện Cái Nước',N'Cai Nuoc District','cai_nuoc','96'),
('970',N'Đầm Dơi',N'Dam Doi',N'Huyện Đầm Dơi',N'Dam Doi District','dam_doi','96'),
('971',N'Năm Căn',N'Nam Can',N'Huyện Năm Căn',N'Nam Can District','nam_can','96'),
('972',N'Phú Tân',N'Phu Tan',N'Huyện Phú Tân',N'Phu Tan District','phu_tan','96'),
('973',N'Ngọc Hiển',N'Ngoc Hien',N'Huyện Ngọc Hiển',N'Ngoc Hien District','ngoc_hien','96');